server:
  port: 8080
  tomcat:
    threads:
      max: 500
    accept-count: 200
    max-connections: 10000


spring:
  data:
    redis:
      # Redis 服务器地址和端口
      host: 192.168.3.195
      port: 6379
      # 密码（如果没有可省略）
      password: 123456

      # 使用的数据库索引（默认是 0）
      database: 10

      # 连接超时时间
      timeout: 5s
      connect-timeout: 5s  # 连接建立超时

      # Lettuce 客户端配置（Spring Boot 3 默认使用 Lettuce）
      lettuce:
        pool:
          enabled: true                    # 启用连接池
          max-active: 200                  # 最大连接数
          max-idle: 50                     # 最大空闲连接
          min-idle: 10                     # 最小空闲连接
          max-wait: 2000ms                 # 获取连接的最大等待时间
